<?php


namespace app\modules\feedback\forms;


use yii\base\Model;

class CallbackForm extends Model
{
    public $name;
    public $phone;

    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }
}
